import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";

const Home: NextPage = () => {
  const { data, isLoading, isError, error } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (isError)
    return <div>{error.message || "Something unexpected ocurred"}</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data?.length > 0 ? (
          <ul>
            {data.map((post) => (
              <li key={post.id}>
                <Link href={`/posts/${post.id}`}>{post.title}</Link>
              </li>
            ))}
          </ul>
        ) : (
          <div>No posts found</div>
        )}
      </main>
    </>
  );
};

export default Home;
